### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ndsvw** [amis92/csharp-source-generators#150]
Hi, I found some broken links:

- [ ] %5B#projects-using-custom-source-generators-internally (file: README.md, status code: 404, the table of content link)
- [ ] https://github.com/beakona/AutoCoder (file: README.md, status code: 404)
- [ ] https://github.com/efonsecab/AutoGeneratedSystem (file: README.md, status code: 404)

**Comment by amis92** [comment]
Thanks for raising this!
