### ISSUE TITLE
New blog regarding the source generator

### ISSUE THREAD

**Issue by yanxiaodi** [amis92/csharp-source-generators#25]
Hi, just published a blog regarding the source generator: https://levelup.gitconnected.com/four-ways-to-generate-code-in-c-including-source-generators-in-net-5-9e6817db425
The demo is: https://github.com/yanxiaodi/MyCodeSamples/tree/main/CodeGeneratorDemo

Not sure if you would contain it on this repo. Thanks for your effort. 👍

**Comment by amis92** [comment]
Hi. Sure, it's an interesting post, add to the Articles section with a summary what the article is about (comparing generation methods).

One comment - I've skimmed through. I think Reflection is not really a generation method. If you want, there's `Reflection.Emit` which is truly runtime-code-generation (emits IL during runtime, into that runtime). But normal reflection doesn't fit your article, in my opinion.

Nevertheless, it's a rich comparison with visible effort put in. I think people will find it useful. Go ahead and open a PR! :)

**Comment by yanxiaodi** [comment]
Thanks @amis92  yes I agree. Actually when I started the article, I just wanted to explain the Source Generators, but I thought it would be meaningful to cover Reflection and T4 as well - since for some scenarios they are doing similar things. Anyway I can add `Reflection.Emit` to the article in the future. Thanks for your comment. I'll make a PR later.
