### ISSUE TITLE
Can you add AutomaticInterface?

### ISSUE THREAD

**Issue by ChristianSauer** [amis92/csharp-source-generators#66]
HI, is was on family leave for some months but I finally managed to improve AutomaticInterface to a working version. 
Can you add this?
https://github.com/codecentric/net_automatic_interface

**Comment by amis92** [comment]
@ChristianSauer It's been here for a year already ;)

**Comment by ChristianSauer** [comment]
@amis92 Sorry I was blind. Expected AutomaticInterface and did not find it :)
